name: Test, Build and Release apk
on: 
  push:
    tags:
      - v*
jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    # - run: flutter test
    - run: flutter build apk
    - run: |
        set -x
        echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: "build/app/outputs/apk/release"
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - run: | 
        set -e
        mv build/app/outputs/apk/release/app-release-unsigned-signed.apk build/app/outputs/apk/release/Yamimo-${{ env.VERSION_TAG }}.apk
        
    - name: Create a Release
      id: create_release
      uses: fregante/release-with-changelog@v3
      with:
        title: Yamimo ${{ env.VERSION_TAG }}
        commit-template: '- {title} ← {hash}'
        template: |
          ### Changelog

          {commits}
        token: ${{ secrets.TOKEN }}

    - name: Upload Release APK
      id: upload-release-apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/apk/release/Yamimo-${{ env.VERSION_TAG }}.apk
        asset_name: Yamimo-${{ env.VERSION_TAG }}.apk
        asset_content_type: application/vnd.android.package-archive